### ISSUE TITLE
Add meta tags for the website

### ISSUE THREAD

**Issue by ssejjemba** [gertruden/educational-website#2]
https://github.com/gertruden/educational-website/blob/1bfa2db2b40dd05b827bfdd3667bc779629c2c11/index.html#L3

Description Tag: This should be a brief summary of the content on the webpage. The description tag should be no more than 155 characters long.

Keyword Tag: This should contain a list of relevant keywords that the webpage is targeting. The keywords should be separated by commas.

Robots Meta Tag: This should be added to control how search engine bots crawl and index the website.

**Comment by gertruden** [comment]
resolved
